/* automatically generated by rust-bindgen 0.69.4 */

extern "C" {
    pub fn ao_fec_crc(bytes: *const u8, len: u8) -> u16;
}
extern "C" {
    pub fn ao_fec_check_crc(bytes: *const u8, len: u8) -> u8;
}
extern "C" {
    pub fn ao_fec_encode(in_: *const u8, len: u8, out: *mut u8) -> u8;
}
extern "C" {
    pub fn ao_fec_decode(
        in_: *const u8,
        in_len: u16,
        out: *mut u8,
        out_len: u8,
        callback: ::std::option::Option<unsafe extern "C" fn() -> u16>,
    ) -> u8;
}
extern "C" {
    pub fn ao_fec_interleave_bytes(in_: *mut u8, len: u16, out: *mut u8) -> u16;
}
